@extends('layout.master')
@section('left_nav')
    @include('includes.super_admin.left_nav')
@endsection
@section('top_nav')
    @include('includes.super_admin.top_nav')
@endsection
@section('statistique')
    @include('includes.super_admin.statistique')
@endsection
